export const COLUMN_INIT_CONFIG = [
  { field: 'country', spanCell: true, sort: 'asc' },
  { field: 'year', spanCell: true, sort: 'asc' },
  { field: 'sport', spanCell: true, sort: 'asc' },
  { field: 'athlete' },
  { field: 'age' },
  { field: 'total' },
  { field: 'date' },
  { field: 'gold' },
  { field: 'silver' },
  { field: 'bronze' },
  { field: 'alpha_score_003' },
  { field: 'beta_score_020' },
  { field: 'gamma_score_037' },
  { field: 'delta_score_054' },
  { field: 'epsilon_score_071' },
  { field: 'zeta_score_088' },
  { field: 'eta_score_105' },
  { field: 'theta_score_122' },
  { field: 'kappa_score_139' },
//   { field: 'lambda_score_156' },
//   { field: 'sigma_score_173' },
//   { field: 'omega_score_190' },
//   { field: 'nova_score_207' },
//   { field: 'apex_score_224' },
//   { field: 'prime_score_241' },
//   { field: 'core_score_258' },
//   { field: 'flux_score_275' },
//   { field: 'pulse_score_292' },
//   { field: 'drift_score_309' },
//   { field: 'spark_score_326' },
//   { field: 'vivid_score_343' },
//   { field: 'rapid_score_360' },
//   { field: 'quiet_score_377' },
//   { field: 'bold_score_394' },
//   { field: 'alpha_index_411' },
//   { field: 'beta_index_428' },
//   { field: 'gamma_index_445' },
//   { field: 'delta_index_462' },
//   { field: 'epsilon_index_479' },
//   { field: 'zeta_index_496' },
//   { field: 'eta_index_513' },
//   { field: 'theta_index_530' },
//   { field: 'kappa_index_547' },
//   { field: 'lambda_index_564' },
//   { field: 'sigma_index_581' },
//   { field: 'omega_index_598' },
//   { field: 'nova_index_615' },
//   { field: 'apex_index_632' },
//   { field: 'prime_index_649' },
//   { field: 'core_index_666' },
//   { field: 'flux_index_683' },
//   { field: 'pulse_index_700' },
//   { field: 'drift_index_717' },
//   { field: 'spark_index_734' },
//   { field: 'vivid_index_751' },
//   { field: 'rapid_index_768' },
//   { field: 'quiet_index_785' },
//   { field: 'bold_index_802' },
//   { field: 'alpha_ratio_819' },
//   { field: 'beta_ratio_836' },
//   { field: 'gamma_ratio_853' },
//   { field: 'delta_ratio_870' },
//   { field: 'epsilon_ratio_887' },
//   { field: 'zeta_ratio_904' },
//   { field: 'eta_ratio_921' },
//   { field: 'theta_ratio_938' },
//   { field: 'kappa_ratio_955' },
//   { field: 'lambda_ratio_972' },
//   { field: 'sigma_ratio_989' },
//   { field: 'omega_ratio_006' },
//   { field: 'nova_ratio_023' },
//   { field: 'apex_ratio_040' },
//   { field: 'prime_ratio_057' },
//   { field: 'core_ratio_074' },
//   { field: 'flux_ratio_091' },
//   { field: 'pulse_ratio_108' },
//   { field: 'drift_ratio_125' },
//   { field: 'spark_ratio_142' },
//   { field: 'vivid_ratio_159' },
//   { field: 'rapid_ratio_176' },
//   { field: 'quiet_ratio_193' },
//   { field: 'bold_ratio_210' },
//   { field: 'alpha_yield_227' },
//   { field: 'beta_yield_244' },
//   { field: 'gamma_yield_261' },
//   { field: 'delta_yield_278' },
//   { field: 'epsilon_yield_295' },
//   { field: 'zeta_yield_312' },
//   { field: 'eta_yield_329' },
//   { field: 'theta_yield_346' },
//   { field: 'kappa_yield_363' },
//   { field: 'lambda_yield_380' },
//   { field: 'sigma_yield_397' },
//   { field: 'omega_yield_414' },
//   { field: 'nova_yield_431' },
//   { field: 'apex_yield_448' },
//   { field: 'prime_yield_465' },
//   { field: 'core_yield_482' },
//   { field: 'flux_yield_499' },
//   { field: 'pulse_yield_516' },
//   { field: 'drift_yield_533' },
//   { field: 'spark_yield_550' },
//   { field: 'vivid_yield_567' },
//   { field: 'rapid_yield_584' },
//   { field: 'quiet_yield_601' },
//   { field: 'bold_yield_618' },
//   { field: 'alpha_grade_635' },
//   { field: 'beta_grade_652' },
//   { field: 'gamma_grade_669' },
//   { field: 'delta_grade_686' },
]
